### ISSUE TITLE
floppy installer backup feature broken

### ISSUE THREAD

**Issue by dajhorn** [shidel/FDI-x86#2]
The FreeDOS 1.3-RC5 floppy installer always fails if the user chooses a system backup:

```
Creating backup of previous OS files to C:\BACKUP.001.

ERROR #1, Subprocess error
Failed.

CRITICAL error: Unable to backup files in target directory.

The installation of FreeDOS 1.3-RC5 has been aborted.
```

**Comment by dajhorn** [comment]
DOSBox-X Screenshot

![FDI-x86 1 5-RC5 Backup Error](https://user-images.githubusercontent.com/494022/146477268-d0f27311-61dd-453a-811c-6e3b3fdfce2c.png)

**Comment by shidel** [comment]
Note to self: There is also a reference to this issue at the FreeDOS archive as [FDI-x86 Issue 4](https://gitlab.com/FreeDOS/OS/FDI-x86/-/issues/4). Once corrected, both will need marked fixed.

**Comment by shidel** [comment]
After investigating the issue, the problem occurs at [Line 226](https://github.com/shidel/FDI-x86/blob/c611cab01623e3d0d4807617affc6c1a44d611fa/SETUP/SETUP.BAT#L225). When **XCOPY** is told to copy an empty directory it returns an error code. When the OS is installed using the FloppyEdition, both **%DOSDIR%\LINKS** and **%DOSDIR%\TEMP** are empty and cause **XCOPY** to generate an error and the backup process to fail. 

Unless an easier work-around can be though of, this will probably require additional functionality added to [**vfdutil**](https://github.com/LoopZ/V8Power/blob/master/SOURCE/VFDUTIL.ASM) to test if a directory is empty. 

Since both FDI and FDI-x86 use a similar method to backup the old DOS files, this issue will also effect the primary installer as well as FDI-x86.

**Comment by shidel** [comment]
With [update to V8PowerTools](https://github.com/LoopZ/V8Power/commit/097bff2f906e2acad11c9d1d27519a534139d446) and a [test for empty directories](https://github.com/shidel/FDI-x86/commit/8487b8a00cd0c05d12782ab0d4e974584c6b0f77) before attempting to use xcopy made within FDI-x86, the issue should be resolved. Just needs testing now.

**Comment by shidel** [comment]
Confirmed, fixed using new build of V8Power Tools. 

Note: Primary installer was not affected by this. It had a different work-around using pipes, dir and vstr to prevent the issue. [FDINS200.BAT](https://github.com/shidel/FDI/blob/5415105b5be3b1bb5f83dcdb98ab5a66e1d34ad7/FDISETUP/SETUP/FDINS200.BAT#L116) in FDI may be updated to use the better solution provided by the VFDUTIL empty directory test.
